# Multi-Cloud Context Validation Module Variables

variable "enabled" {
  description = "Set to false to prevent the module from creating any resources or performing validation"
  type        = bool
  default     = true
}

variable "name_prefix" {
  description = "Organization unique prefix to use for resource names. Generated by terraform-external-context module."
  type        = string
  validation {
    condition     = can(regex("^[a-zA-Z][a-zA-Z0-9-]{0,62}[a-zA-Z0-9]$", var.name_prefix))
    error_message = "The name_prefix value must start with a letter, followed by 0 to 62 alphanumeric or hyphen characters, ending with alphanumeric, for a total length of 2 to 64 characters."
  }
}

variable "tags" {
  description = "Tags/labels to apply to all resources (generated by terraform-external-context)"
  type        = map(string)
  default     = {}
}

variable "cloud_provider" {
  description = "Cloud provider identifier (aws, azure, gcp). Auto-detected if not specified."
  type        = string
  default     = null
  validation {
    condition     = var.cloud_provider == null || contains(["aws", "azure", "gcp"], var.cloud_provider)
    error_message = "Cloud provider must be one of: aws, azure, gcp."
  }
}

variable "random_suffix" {
  description = "Random suffix for globally unique resource names (e.g., from random_id.hex)"
  type        = string
  default     = "12345678"
  validation {
    condition     = can(regex("^[a-z0-9]{8}$", var.random_suffix))
    error_message = "Random suffix must be 8 characters of lowercase letters and numbers."
  }
}

variable "enforce_cross_cloud_compatibility" {
  description = "Whether to enforce cross-cloud compatibility constraints (more restrictive)"
  type        = bool
  default     = false
}

variable "validate_required_tags" {
  description = "Whether to validate that required tags/labels are present for the cloud provider"
  type        = bool
  default     = false
}

variable "custom_constraints" {
  description = "Custom validation constraints to override defaults"
  type = object({
    max_name_length = optional(number)
    name_pattern    = optional(string)
    max_tags        = optional(number)
    required_tags   = optional(list(string))
  })
  default = {}
}

# Environment-specific configuration
variable "environment_type" {
  description = "Environment type for resource configuration defaults"
  type        = string
  default     = "Development"
  validation {
    condition = contains([
      "None", "Ephemeral", "Development", "Testing", "UAT", "Production", "MissionCritical"
    ], var.environment_type)
    error_message = "Environment type must be one of: None, Ephemeral, Development, Testing, UAT, Production, MissionCritical."
  }
}

# Resource-specific validation flags
variable "validate_storage_resources" {
  description = "Whether to validate storage resource naming (S3, Storage Account, Cloud Storage)"
  type        = bool
  default     = true
}

variable "validate_compute_resources" {
  description = "Whether to validate compute resource naming (EC2, VM, Compute Engine)"
  type        = bool
  default     = true
}

variable "validate_iam_resources" {
  description = "Whether to validate IAM resource naming (IAM roles, Service Accounts)"
  type        = bool
  default     = true
}